### ISSUE TITLE
first release in maven repo?

### ISSUE THREAD

**Issue by arolfes** [quarkiverse/quarkus-pact#33]
Hello @holly-cummins ,

when do you plan to have a first release in maven central repo?

Best Regards
Alex

**Comment by holly-cummins** [comment]
Hi Alex, thanks for the nudge. I've been meaning to do it for several days but kept getting sidetracked. :) (I was initially waiting for #29, which fixes #11, so that the extension offered something over running with a normal dependency). I'll try to do it today. 

Be aware that 
 - it will only be for pact provider, not the consumer ... consumer will be early in the new year (I hope)
 - #28 is still a problem, so that the extension needs to be added *without* `test` scope, even though `test` scope is obviously the correct scope for a pact extension

**Comment by holly-cummins** [comment]
Hi Alex, both consumer and provider extensions are now released. 

```
    <dependency>
      <groupId>io.quarkiverse.pact</groupId>
      <artifactId>quarkus-pact-provider</artifactId>
      <version>0.2</version>
      <!-- <scope>test</scope>--> <!-- See https://github.com/quarkiverse/quarkus-pact/issues/28; for dev mode tests, the scope cannot be test -->
    </dependency>
```

```
    <dependency>
      <groupId>io.quarkiverse.pact</groupId>
      <artifactId>quarkus-pact-consumer</artifactId>
      <version>0.2</version>
      <!-- <scope>test</scope>--> <!-- See https://github.com/quarkiverse/quarkus-pact/issues/28; for dev mode tests, the scope cannot be test -->
    </dependency>
```

**Comment by arolfes** [comment]
Thank you very much

I tried the consumer today.

Works as expected.
